config/routes.rb
Rails.application.routes.draw do
	get 'cervezas/reporte'
  resources :cervezas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cerveza.rb
class Cerveza < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cervezas_controller.rb
class CervezasController < ApplicationController
  before_action :set_cerveza, only: [:show, :edit, :update, :destroy]

  # GET /cervezas
  # GET /cervezas.json
  def index
    @cervezas = Cerveza.all
  end

  # GET /cervezas/1
  # GET /cervezas/1.json
  def show
  end

  # GET /cervezas/new
  def new
    @cerveza = Cerveza.new
  end

  # GET /cervezas/1/edit
  def edit
  end

  # POST /cervezas
  # POST /cervezas.json
  def create
    @cerveza = Cerveza.new(cerveza_params)

    respond_to do |format|
      if @cerveza.save
        format.html { redirect_to @cerveza, notice: 'Cerveza was successfully created.' }
        format.json { render :show, status: :created, location: @cerveza }
      else
        format.html { render :new }
        format.json { render json: @cerveza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cervezas/1
  # PATCH/PUT /cervezas/1.json
  def update
    respond_to do |format|
      if @cerveza.update(cerveza_params)
        format.html { redirect_to @cerveza, notice: 'Cerveza was successfully updated.' }
        format.json { render :show, status: :ok, location: @cerveza }
      else
        format.html { render :edit }
        format.json { render json: @cerveza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cervezas/1
  # DELETE /cervezas/1.json
  def destroy
    @cerveza.destroy
    respond_to do |format|
      format.html { redirect_to cervezas_url, notice: 'Cerveza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reporte
    @cervezas = Cerveza.all
    @cervezaVolumen = @cervezas.sort_by(&:volumen)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cerveza
      @cerveza = Cerveza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cerveza_params
      params.require(:cerveza).permit(:nombre, :volumen)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cervezas_helper.rb
module CervezasHelper
end

app/views/cervezas/_form.html.erb
<%= form_with(model: cerveza, local: true) do |form| %>
  <% if cerveza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cerveza.errors.count, "error") %> prohibited this cerveza from being saved:</h2>

      <ul>
      <% cerveza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :cerveza_nombre %>
  </div>

  <div class="field">
    <%= form.label :volumen %>
    <%= form.text_field :volumen, id: :cerveza_volumen %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cervezas/edit.html.erb
<h1>Editing Cerveza</h1>

<%= render 'form', cerveza: @cerveza %>

<%= link_to 'Show', @cerveza %> |
<%= link_to 'Back', cervezas_path %>

app/views/cervezas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cervezas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Volumen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cervezas.each do |cerveza| %>
      <tr>
        <td><%= cerveza.nombre %></td>
        <td><%= cerveza.volumen %></td>
        <td><%= link_to 'Show', cerveza %></td>
        <td><%= link_to 'Edit', edit_cerveza_path(cerveza) %></td>
        <td><%= link_to 'Destroy', cerveza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cerveza', new_cerveza_path %>

app/views/cervezas/new.html.erb
<h1>New Cerveza</h1>

<%= render 'form', cerveza: @cerveza %>

<%= link_to 'Back', cervezas_path %>

app/views/cervezas/reporte.html.erb
<% @cervezaVolumen.each do |cerveza| %>
	<%= cerveza.nombre %>
<% end %>

app/views/cervezas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cerveza.nombre %>
</p>

<p>
  <strong>Volumen:</strong>
  <%= @cerveza.volumen %>
</p>

<%= link_to 'Edit', edit_cerveza_path(@cerveza) %> |
<%= link_to 'Back', cervezas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppPg</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>